# Generated by Django 4.2.3 on 2023-10-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BuyShare',
        ),
    ]
