# Generated by Django 4.2.3 on 2023-11-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0006_alter_buyshare_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyshare',
            name='price',
            field=models.DecimalField(decimal_places=12, max_digits=100),
        ),
        migrations.AlterField(
            model_name='sellshare',
            name='price',
            field=models.DecimalField(decimal_places=12, max_digits=100),
        ),
    ]
