# Generated by Django 4.2.3 on 2023-10-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0002_remove_userwallet_id_alter_userwallet_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=255)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeApi.userwallet')),
            ],
        ),
    ]
