# Generated by Django 4.2.3 on 2023-10-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0005_alter_userwallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyshare',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
